### PR TITLE
Add github-markdown-css as Dev Dependency

### PR DESCRIPTION
**Pull request by mamhoff**
Without this, I have not been able to run grunt.

### CODE REVIEW

**Comment by alpipego** [comment]
The `github-markdown-css` should be contained in the package `generate-github-markdown-css`. Could you please get the latest upstream, remove your `node_modules` and reinstall node packages, cf #20.

**Comment by mamhoff** [comment]
Done that - I still get: 
```
➜  tech-website git:(master) grunt                        
Running "clean:default" (clean) task
>> 2 paths cleaned.

Running "sass:default" (sass) task
>> Error: File to import not found or unreadable: ../../node_modules/github-markdown-css/github-markdown.
>>         on line 1 of assets/scss/github.scss
>> >> @import "../../node_modules/github-markdown-css/github-markdown";
>> 
>>    ^
Warning:  Use --force to continue.

Aborted due to warnings.
```

It seems to me the `generate-` package helps one generate that CSS, but the code in the project seems to assume it's already there.

**Comment by alpipego** [comment]
Could you please open an issue? It seems that this should be handled on scss level. Thank you.

**Comment by mamhoff** [comment]
Add #24 , closing this for now.

**Pull request closed without merging**
